eshopSolution.AdminAPP/Controllers/LoginAppController.cs
using eshopSolution.AdminAPP.Service;
using eShopSolution.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace eshopSolution.AdminAPP.Controllers
{
    public class LoginAppController : Controller
    {
        private readonly IUserApiClient _iuserApiClient;
        private readonly IConfiguration _configuration;

        public LoginAppController(IUserApiClient iuserApiClient, IConfiguration configuration)
        {
            _iuserApiClient = iuserApiClient;
            _configuration = configuration;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest request)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var token = await _iuserApiClient.Authenticate(request);
            if (token.ResultObj == null)
            {
                ModelState.AddModelError("", token.Message);
                return View();
            }
            var userprincical = this.ValidateToken((string)token.ResultObj);
            var authproperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30),
                IsPersistent = true
            };
            HttpContext.Session.SetString("DefaultLanguageId", _configuration["DefaultLanguageId"]);
            HttpContext.Session.SetString("Token", token.ResultObj);
            var claims = userprincical.Claims.ToList();
            foreach (var claim in claims)
            {
                if (claim != null && claim.ToString().Contains("admin"))
                {
                    HttpContext.Session.SetString("Roles", claim.ToString());
                    await HttpContext.SignInAsync(
               CookieAuthenticationDefaults.AuthenticationScheme,
               userprincical,
               authproperties);
                    return RedirectToAction("Index", "Home");
                }
            }
            TempData["result"] = "User role is not admin.";
            return RedirectToAction("Login");
        }

        private ClaimsPrincipal ValidateToken(string JwtToken)
        {
            IdentityModelEventSource.ShowPII = true;
            SecurityToken Issuer;
            TokenValidationParameters validationParameters = new TokenValidationParameters();
            validationParameters.ValidateLifetime = true;
            validationParameters.ValidAudience = _configuration["Tokens:Issuer"];
            validationParameters.ValidIssuer = _configuration["Tokens:Issuer"];
            byte[] signingKeyBytes = Encoding.UTF8.GetBytes(_configuration["Tokens:Key"]);
            validationParameters.IssuerSigningKey = new SymmetricSecurityKey(signingKeyBytes);
            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(JwtToken, validationParameters, out Issuer);
            return principal;
        }
    }
}

eshopSolution.AdminAPP/Controllers/RegisterAppController.cs
using eshopSolution.AdminAPP.Service;
using eShopSolution.ViewModels.System.Users;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eshopSolution.AdminAPP.Controllers
{
    public class RegisterAppController : Controller
    {
        private readonly IUserApiClient _iuserApiClient;

        public RegisterAppController(IUserApiClient iuserApiClient)
        {
            _iuserApiClient = iuserApiClient;
        }

        [HttpGet]
        public IActionResult Register()
        {
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);
                var result = await _iuserApiClient.register(request);
                if (result.IsSuccessed == true)
                {
                    TempData["result"] = "Register Successfully!";
                    return RedirectToAction("Register");
                }
                TempData["result"] = result.Message;
                return RedirectToAction("Register");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

eshopSolution.AdminAPP/Views/RegisterApp/Register.cshtml
@using eShopSolution.ViewModels.System.Users;
@model RegisterRequest
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Register - SB Admin</title>
    <link href="/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body class="bg-primary">
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Account</h3></div>
                                <div class="row">
                                    <div class="col-md-6" style="height:auto">
                                        @if (TempData["result"] != null)
                                        {
                                            <div id="msgAlert" class="alert alert-success" role="alert">
                                                @ViewBag.SuccessMsg
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div class="card-body">
                                    <form asp-controller="registerapp" asp-action="register" method="post">
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input class="form-control" asp-for="FirstName" type="text" placeholder="Enter your first name" />
                                                    <label>First name</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-floating">
                                                    <input class="form-control" asp-for="LastName" type="text" placeholder="Enter your last name" />
                                                    <label>Last name</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" asp-for="Dob" type="datetime-local" placeholder="Day Of birthday" />
                                            <label>DoB</label>
                                        </div>

                                        <div class="form-floating mb-3">
                                            <input class="form-control" asp-for="email" type="email" placeholder="name@example.com" />
                                            <label>Email address</label>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" asp-for="UserName" type="text" placeholder="User Name" />
                                            <label>User Name</label>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input class="form-control" asp-for="Password" type="password" placeholder="Create a password" />
                                                    <label>Password</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input class="form-control" asp-for="ConfirmPassword" type="password" placeholder="Confirm password" />
                                                    <label>Confirm Password</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="mt-4 mb-0">
                                            <div class="d-grid"><button class="btn btn-primary btn-block" type="submit">Create Account</button></div>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a asp-controller="LoginApp" asp-action="Login">Have an account? Go to login</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="/assets/demo/chart-area-demo.js"></script>
    <script src="/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="/js/datatables-simple-demo.js"></script>
</body>
</html>