eshopSolution.AdminAPP/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eshopSolution.AdminAPP.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PaginationBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eshopSolution.AdminAPP/Controllers/UserAppController.cs
using eshopSolution.AdminAPP.Service;
using eShopSolution.ViewModels.Common;
using eShopSolution.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace eshopSolution.AdminAPP.Controllers
{
    public class UserAppController : BaseController
    {
        private readonly IUserApiClient _iuserApiClient;
        private readonly IRoleApiClient _iroleApiClient;
        private readonly IConfiguration _configuration;

        public UserAppController(IUserApiClient iuserApiClient, IRoleApiClient iroleApiClient, IConfiguration configuration)
        {
            _iuserApiClient = iuserApiClient;
            _iroleApiClient = iroleApiClient;
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string keyword, int pageindex = 1, int pagsize = 10)
        {
            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageindex,
                PageSize = pagsize,
            };
            var data = await _iuserApiClient.Listuser(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }

            return View(data.ResultObj);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Login", "LoginApp");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _iuserApiClient.UserbyId(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updaterequest = new UserUpdateRequest()
                {
                    id = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Dob = user.Dob,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber
                };
                return View(updaterequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var result = await _iuserApiClient.UpdateUser(request.id, request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Update Successfully!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        //[HttpGet]
        //public IActionResult Delete(Guid id)
        //{
        //    return View(new UserDeleteRequest()
        //    {
        //        Id = id
        //    });
        //}

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _iuserApiClient.DeleteUser(id);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Delete successfully!";
                //return RedirectToAction("Index");
                return Json(TempData["result"].ToString());
            }

            ModelState.AddModelError("", result.Message);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(Guid id)
        {
            var result = await _iuserApiClient.UserbyId(id);
            return View(result.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> SuggestSearch()
        {
            string keyword = HttpContext.Request.Query["term"].ToString();
            var result = await _iuserApiClient.SuggestSearch(keyword);
            if (result.IsSuccessed)
            {
                return Ok(result.ResultObj);
            }
            return Ok(result.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> RolesAssign(Guid Id)
        {
            var roles = HttpContext.Session.GetString("Roles");
            if (roles != null && roles.Contains("admin"))
            {
                var roleAssignRequst = await GetRoleAssignRequest(Id);
                return View(roleAssignRequst);
            }
            TempData["result"] = "The user role is not administrator.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RolesAssign(RoleAssignRequest request)
        {
            var roles = HttpContext.Session.GetString("Roles");
            if (roles != null && roles.Contains("admin"))

            {
                if (!ModelState.IsValid)
                    return View();
                var result = await _iuserApiClient.RoleAssign(request.Id, request);
                if (result.IsSuccessed)
                {
                    TempData["result"] = "Assign Successfully!";
                    return RedirectToAction("Index", "UserApp");
                }
                ModelState.AddModelError("", result.Message);
                var roleAssignRequst = await GetRoleAssignRequest(request.Id);
                return View(roleAssignRequst);
            }
            TempData["result"] = "The user role is not administrator.";
            return RedirectToAction("Index");
        }

        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid Id)
        {
            var userObj = await _iuserApiClient.UserbyId(Id);
            var roleObj = await _iroleApiClient.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            foreach (var role in roleObj.ResultObj)
            {
                roleAssignRequest.Roles.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = userObj.ResultObj.Roles.Contains(role.Name),
                });
            }
            return roleAssignRequest;
        }
    }
}

eshopSolution.AdminAPP/Views/UserApp/Delete.cshtml
@model eShopSolution.ViewModels.System.Users.UserDeleteRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>
<hr />
<h3>Are you sure you want to delete this?</h3>
<div style="margin-left:3px">

    <form asp-action="Delete" method="post">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button asp-action="Index" class="btn btn-primary">Cancel</button>
    </form>
</div>

eshopSolution.AdminAPP/Views/UserApp/Detail.cshtml
@model eShopSolution.ViewModels.System.Users.UserVM

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail: @Html.DisplayFor(Model => Model.UserName)</h1>

<div class="container-fluid px-4">
    <div class="card mb-4">
    </div>
    <div class="card mb-4">

        <div class="card-body">
            <table class="table table-bordered" style="width:auto">
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.FirstName)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.LastName)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Dob)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Dob)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Email)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.CreatedAt)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.CreatedAt)
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

eshopSolution.AdminAPP/Views/UserApp/Edit.cshtml
@model eShopSolution.ViewModels.System.Users.UserUpdateRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Edit</h1>
<hr />
<div class="container-fluid px-4">
    <div class="card mb-4">
        <div class="card-body">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <table class="table table-bordered" style="width:auto">
                    <tr>
                        <th class="col-sm-2">
                            <label asp-for="FirstName" class="control-label"></label>
                        </th>
                        <td class="col-sm-10">
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </td>


                    </tr>
                    <tr>
                        <th class="col-sm-2">
                            <label asp-for="LastName" class="control-label"></label>
                        </th>
                        <td class="col-sm-10">
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-sm-2">
                            <label asp-for="Dob" class="control-label"></label>
                        </th>
                        <td class="col-sm-10">
                            <input asp-for="Dob" class="form-control" />
                            <span asp-validation-for="Dob" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-sm-2">
                            <label asp-for="Email" class="control-label"></label>

                        </th>
                        <td class="col-sm-10">
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-sm-2">
                            <label asp-for="PhoneNumber" class="control-label"></label>

                        </th>
                        <td class="col-sm-10">
                            <input asp-for="PhoneNumber" class="form-control" type="number"/>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </td>
                    </tr>
                </table>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>

        </div>
    </div>
</div>

eshopSolution.AdminAPP/Views/UserApp/Index.cshtml
@using eShopSolution.ViewModels.Common;
@model PagedResult<eShopSolution.ViewModels.System.Users.UserVM>

@{
    ViewData["Title"] = "Danh Sách Người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        $(document).ready(function () {
            $('#searching').autocomplete({
                source: '/UserApp/SuggestSearch'
            });
        });
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);

        var ConfirmDelete = function (userid) {
            console.log(userid);
            $("#hideuserid").val(userid);
            $("#deleteuserModal").modal('show');
        }

        var Close = function () {
            $("#myModal").modal('hide');
            $('#myModal').insertAfter($('body'));
        }

        var DeleteUser = function () {
            $("#deleteuserModal").hide();
            var userId = $("#hideuserid").val();           
            $.ajax({
                type: "POST",
                url: "/UserApp/Delete",
                data: { id: userId },
                success: function (result) {                                   
                    $("#deleteuserModal").modal("hide");                     
                    $("#row_" + userId).remove();
                    $("#notificationDeleted").css("display", "block");
                    setTimeout(function () {
                        $("#notificationDeleted").fadeOut('slow');
                        //window.location.href = "/ProductsApp/Index/";
                    }, 4000);
                },
                error: function () {
                    alert("Error");
                }

            });
        }
    </script>
}

<input type="hidden" id="hideuserid" />
<div class="modal" id="deleteuserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Product</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>Are you sure ? You want to delete this. </h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="DeleteUser()">Delete</button>
            </div>
        </div>
    </div>
</div>


<div class="row alert alert-success" style="margin-top: 10px; float: right; width: 10%; margin-right: 30px; display:none" id="notificationDeleted">
    Delete successfully!
</div>
<div class="row" style="margin-top: 10px; float: right; width: 20%; ">

    @if (TempData["result"] != null)
    {
        <div id="msgAlert" class="alert alert-success" role="alert">
            @ViewBag.SuccessMsg
        </div>
    }
</div>
<div class="container-fluid px-4">
    <h1 class="mt-4">Danh Sách Người Dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Danh Sách Người Dùng</li>
    </ol>

    <div class="card mb-4">
        <div class="card mb-12">

            <div class="card-header">
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <form asp-action="Index" method="get">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-6" style="float:left">
                                        <input id="searching" type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" placeholder="User or Email" />
                                    </div>
                                    <div class="col-md-3" style="float:left; padding-left:5px">
                                        <button type="submit" class="btn btn-primary">Tìm</button>
                                        <button type="button" onclick="window.location.href='/Userapp/Index'" class="btn btn-dark">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <div class="row">
                </div>

                <table class="table table-bordered " id="datatables">
                    <thead>
                        <tr>
                            <th>
                                UserName
                            </th>
                            <th>
                                DoB
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                CreatedAt
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr id="row_@item.Id">
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Dob)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedAt)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Detail", "Detail", new { id = item.Id }) |
                                    @*@Html.ActionLink("Delete", "Delete", new { id = item.Id }) |*@
                                    @Html.ActionLink("Roles Assign", "RolesAssign", new { id = item.Id }) |
                                    <a class="btn btn-danger" onclick="ConfirmDelete('@item.Id')">Delete <i class="glyphicon-trash"></i>  </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div style="padding-left:40%; padding-right:50%;width:250px">@await Component.InvokeAsync("Pager", Model)</div>
        </div>
    </div>
</div>

eshopSolution.AdminAPP/Views/UserApp/RolesAssign.cshtml
@model eShopSolution.ViewModels.System.Users.RoleAssignRequest

@{
    ViewData["Title"] = "RolesAssign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<hr />
<div class="container-fluid px-4">
    <div class="card mb-4">
    </div>
    <div class="card mb-4">

        <div class="card-body">
            <form asp-action="RolesAssign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                @for (var i = 0; i < Model.Roles.Count; i++)
                {
            <div class="form-group">
                @Model.Roles[i].Name
                <input type="checkbox" asp-for="Roles[i].Selected" />
                <input type="hidden" asp-for="Roles[i].Id" />
                <input type="hidden" asp-for="Roles[i].Name" />
            </div>
                }

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>